# Generated by Django 4.2.4 on 2023-10-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_banlk_card_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='stk',
            field=models.BigIntegerField(default=0),
        ),
    ]
